apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Values.labels.app }}
    project: {{ .Values.labels.project }}
    environment: {{ .Values.labels.environment }}
    owner: {{ .Values.labels.owner }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        project: {{ .Values.labels.project }}
        environment: {{ .Values.labels.environment }}
        owner: {{ .Values.labels.owner }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
