apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-nodeport
  labels:
    app: {{ .Values.labels.app }}
    project: {{ .Values.labels.project }}
    environment: {{ .Values.labels.environment }}
    owner: {{ .Values.labels.owner }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
